services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/www:/var/www/html
    depends_on:
      - app
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    expose:
      - "3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://user:password@db:5432/users?schema=public"
      NEXTAUTH_SECRET: "NcvPotx8wB4UuDxOpfyXVNHf1n+7kxcQ0IiOdHkdyDU="
      NEXTAUTH_URL: "http://next.leopoldcanou.fr"
    restart: always
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

volumes:
  db-data: 